### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by satishtaluru** [SAP/C4CODATAAPIDEVGUIDE#19]
In JSON response date format coming as Date(1351534600660)  how to convert date-time.

**Comment by ultruder** [comment]
I parse this with a regex that only takes the numbers. You could convert it, for example, using Instant.ofEpochMilli().

**Comment by MustafaCa** [comment]
JSON date/datetime indicates the milliseconds passed since Jan 1, 1970.
Please check - https://stackoverflow.com/questions/1244094/converting-json-results-to-a-date for a solution using JavaScript.
