### ISSUE TITLE
Filter not applicable to Appointment start datetime

### ISSUE THREAD

**Issue by Jaganm70** [SAP/C4CODATAAPIDEVGUIDE#2]
I am trying to filter AppointmentCollection based on Field StartDateTime. But it return 500 SAP Internal Server Error.
Ex:- $filter=StartDateTime/content ge datetimeoffset'2016-07-08T00:00:00Z'

**Comment by venkyvb** [comment]
Please report an incident for this issue from your C4C tenant.
