### ISSUE TITLE
Broken links to help.sap.com in README.md (403/forbidden in SAP Help Portal)

### ISSUE THREAD

**Issue by mydoghasworms** [SAP/C4CODATAAPIDEVGUIDE#26]
The links to the help.sap.com documentation in the README.md file lead to pages on the SAP Help Portal that have no content and give a popup with a 403 message (see image below).

The links referred to are the following:

![image](https://user-images.githubusercontent.com/514461/110584073-57db1900-8177-11eb-836c-13507fecd2be.png)

The resulting pages on the SAP Help Portal look like this (note the 403 message - "403: You don't have rights to view this page"):

![image](https://user-images.githubusercontent.com/514461/110584262-9a9cf100-8177-11eb-9823-e5bad8267943.png)

**Comment by venkyvb** [comment]
@MustafaCa maybe it would make sense to set the link to - https://help.sap.com/doc/d0f9ba822c08405da7d88174b304df84/CLOUD/en-US/index.html#/

**Comment by mydoghasworms** [comment]
Well thanks, that helps me already somewhat 😉

**Comment by MustafaCa** [comment]
Thanks Martin. I updated the document with the correct links.

@Venki: Thanks! Long time, no talk! Hope all is well with you. :-)

**Comment by mydoghasworms** [comment]
@MustafaCa Thank you, I can confirm that the links are working now.
I trust it is OK for me to close the issue?
