### ISSUE TITLE
Not able to understand docs

### ISSUE THREAD

**Issue by Anmol-Tuple** [SAP/C4CODATAAPIDEVGUIDE#4]
Hi, i need to implement the OData to fetch data from sap to our database but not able to understand the docs. Could u provide some examples how to do it?
Moreover, i am not able to understand authentication mechanism can u make it clearer

**Comment by MustafaCa** [comment]
@Anmol-Tuple Please send me an email at mustafa.saglam@sap.com so that we can arrange a call.
