### ISSUE TITLE
Authentication options count

### ISSUE THREAD

**Issue by VishnAndr** [SAP/C4CODATAAPIDEVGUIDE#5]
Please fix [https://github.com/SAP/C4CODATAAPIDEVGUIDE#authentication](https://github.com/SAP/C4CODATAAPIDEVGUIDE#authentication):
.....supports **two different authentication** mechanisms.....

but listed 4.

**Comment by MustafaCa** [comment]
Hi Andrei,

Thanks for letting me know. I just corrected it.

Regards,
Mustafa.
