### ISSUE TITLE
2600188 - Error "Operands of Logical Operator 'and' are not Valid" While Using OData Filters

### ISSUE THREAD

**Issue by sambarza** [SAP/C4CODATAAPIDEVGUIDE#6]
Hi,

Note 2600188 explain the use of AND operator:

> Logical operator AND only works when used between different properties.
> Not Supported:
> $filter=PartyID ge 'ZZZZ' and PartyID le 'XXXX'

But one example in github is:

> ge, le | /OpportunityCollection?$filter=AccountID ge '1001910' and AccountID le '1001920'

I think the oss note is correct, do you agree?

Thanks
Sam

**Comment by MustafaCa** [comment]
Hi Sam,

I am not sure about that OSS note as most likely it is referring to a different SAP product. In the case of C4C, the AND operation can be combined with ge and le for the same property to define a range of values. Thus, the example you are referring above would work as expected. More information on $filter support is available at https://github.com/SAP/C4CODATAAPIDEVGUIDE#filter.

Regards,
Mustafa.

**Comment by sambarza** [comment]
Hi Mustafa,

The OSS note is about C4C and refers to this blog for more info:

![image](https://user-images.githubusercontent.com/3630051/45158789-5bc40400-b1e5-11e8-8fcf-1c0d6993697c.png)

However we tried with this request:
https://XXXXXXX.crm.ondemand.com/sap/c4c/odata/v1/activity/VisitCollection?$filter=EndDateTime%20le%20datetimeoffset%272018-07-06T23:59:59Z%27%20and%20EndDateTime%20gt%20datetimeoffset%272018-07-06T00:00:00Z%27

And we get:

  | <?xml version="1.0" encoding="utf-8"?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code/><message xml:lang="en">Operands of logical operator 'and' are not valid</message></error>
-- | --

Thank you
Sam

**Comment by MustafaCa** [comment]
Your problem is due to the logical operator '**gt**' not being supported. If you replace that with '**ge**' it should work. Please see the link I shared above for supported operators.

Regards,
Mustafa.

**Comment by sambarza** [comment]
Hi Mustafa,

You are right! Now I can also understand better the error message!

So the discrepancy is in the cause section of the oss note:

> Cause
>
> This is the expected system behavior. Logical operator AND only works when used between different properties.
>
> Supported:
> 
> $filter=OpportunityID ge 'YYYY' and Name/content eq 'Test'
> 
> Not Supported:
> 
> $filter=PartyID ge 'ZZZZ' and PartyID le 'XXXX'
> 
> (YYYY represents the ID of the Opportunity, ZZZZ represents one Party ID and XXXX represents another Party ID)

I will report this by an incident too.

Thank you

Best Regards,
Sam
